# Generated by Django 4.2.16 on 2024-10-31 08:15

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="productimage", name="product",),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="Products.productimage"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/category_images/",
                validators=[Products.models.ImageOrSVGValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="media/product_images/"),
        ),
    ]
