# Generated by Django 4.2.16 on 2024-10-31 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0002_remove_productimage_product_product_images_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productimage", options={"verbose_name_plural": "Product Images"},
        ),
        migrations.RemoveField(model_name="product", name="images",),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="product.jpg", upload_to="Product"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(default="product.jpg", upload_to="product-images"),
        ),
    ]
