# Generated by Django 4.2.16 on 2024-10-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0003_alter_product_options_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product-images"),
        ),
    ]
