# Generated by Django 4.2.16 on 2024-10-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0004_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="Product"),
        ),
    ]
