# Generated by Django 4.2.16 on 2024-10-31 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0005_alter_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="order_date", new_name="created_at",
        ),
        migrations.RemoveField(model_name="order", name="order_status",),
        migrations.RemoveField(model_name="order", name="product_name",),
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("cart", "Cart"), ("order", "Order")],
                default="cart",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.product",
                    ),
                ),
            ],
        ),
    ]
